# Generated by Django 3.1.6 on 2021-02-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
